server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.95.155:3306/ssrms-db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ssrms-admin
    password: 8u6NKBb1ubbEyWxBjXda

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ssrms.entity

ssrms:
  cors:
    allowed-origin-patterns: "http://localhost:*,http://127.0.0.1:*,http://你的前端域名,https://你的前端域名"

coze:
  base-url: "https://api.coze.cn"
  bot-id: "7531269592158257204"
  token: "sat_w3Dfmxnsvggf3rgiKm5u2uAzjMrLRXwm8PTN2rT2iaxa0kcxXurcAFMEsY76wRbd"
  connect-timeout-ms: 15000
  read-timeout-ms: 60000
