server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssrms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: fzh586176

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.ssrms.entity

ssrms:
  cors:
    allowed-origin-patterns: "http://localhost:*,http://127.0.0.1:*,http://你的前端域名,https://你的前端域名"